// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using google_keep.Models;

namespace google_keep.Migrations
{
    [DbContext(typeof(NoteContext))]
    [Migration("20180803031922_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("google_keep.Models.CheckList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Check");

                    b.Property<int?>("NoteId");

                    b.Property<bool>("isChecked");

                    b.HasKey("Id");

                    b.HasIndex("NoteId");

                    b.ToTable("CheckList");
                });

            modelBuilder.Entity("google_keep.Models.Labels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("NoteId");

                    b.Property<string>("label");

                    b.HasKey("Id");

                    b.HasIndex("NoteId");

                    b.ToTable("Labels");
                });

            modelBuilder.Entity("google_keep.Models.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Pinned");

                    b.Property<string>("Title");

                    b.Property<string>("text");

                    b.HasKey("Id");

                    b.ToTable("Note");
                });

            modelBuilder.Entity("google_keep.Models.CheckList", b =>
                {
                    b.HasOne("google_keep.Models.Note")
                        .WithMany("checklist")
                        .HasForeignKey("NoteId");
                });

            modelBuilder.Entity("google_keep.Models.Labels", b =>
                {
                    b.HasOne("google_keep.Models.Note")
                        .WithMany("labels")
                        .HasForeignKey("NoteId");
                });
#pragma warning restore 612, 618
        }
    }
}
